import type { StrapiSlide, StrapiStat, StrapiTestimonial } from "@/lib/api";

export const FALLBACK_SLIDES: StrapiSlide[] = [
  {
    id: 1,
    badge: "Education - Nigeria",
    title: "300 enfants ont",
    subtitle: "retrouve le chemin",
    description: "Construction d une ecole primaire complete dans la region de Kano.",
    ctaLabel: "Voir le projet",
    ctaHref: "/projets",
    statValue: "300",
    statLabel: "enfants scolarises",
    order: 1,
  },
  {
    id: 2,
    badge: "Eau Potable - Mali",
    title: "2 500 personnes ont",
    subtitle: "acces a l eau",
    description: "Installation de 12 points d eau dans 5 villages isoles du Sahel.",
    ctaLabel: "Voir le projet",
    ctaHref: "/projets",
    statValue: "12",
    statLabel: "points d eau installes",
    order: 2,
  },
  {
    id: 3,
    badge: "Sante - RD Congo",
    title: "1 200 patients",
    subtitle: "soignes chaque",
    description: "Rehabilitation d un centre de sante au Kivu.",
    ctaLabel: "Voir le projet",
    ctaHref: "/projets",
    statValue: "1 200",
    statLabel: "patients par mois",
    order: 3,
  },
  {
    id: 4,
    badge: "Logement - Haiti",
    title: "150 familles ont",
    subtitle: "un toit",
    description: "Programme de reconstruction de logements durables en Haiti.",
    ctaLabel: "Voir le projet",
    ctaHref: "/projets",
    statValue: "150",
    statLabel: "familles relogees",
    order: 4,
  },
  {
    id: 5,
    badge: "Impact Global",
    title: "35 pays,",
    subtitle: "une seule mission",
    description: "Help Funds opere dans 35 pays pour apporter une aide concrete.",
    ctaLabel: "Notre impact",
    ctaHref: "/projets",
    statValue: "35",
    statLabel: "pays d intervention",
    order: 5,
  },
  {
    id: 6,
    badge: "Ensemble",
    title: "Chaque don",
    subtitle: "change une vie",
    description: "98% de chaque don va directement sur le terrain.",
    ctaLabel: "Faire un don",
    ctaHref: "/don",
    statValue: "98%",
    statLabel: "des dons sur le terrain",
    order: 6,
  },
];

export const FALLBACK_STATS: StrapiStat[] = [
  { id: 1, value: "50 000+", label: "beneficiaires aides", icon: "users", order: 1 },
  { id: 2, value: "120+", label: "projets realises", icon: "folder", order: 2 },
  { id: 3, value: "35", label: "pays touches", icon: "globe", order: 3 },
  { id: 4, value: "98%", label: "des dons sur le terrain", icon: "heart", order: 4 },
];

export const FALLBACK_TESTIMONIALS: StrapiTestimonial[] = [
  {
    id: 1,
    name: "Ama Koffi",
    role: "Mere de famille, Togo",
    text: "Avant cette aide, nous devions parcourir 45 kilometres pour acceder aux vaccins. Maintenant, les medecins viennent a nous.",
    avatar: "AK",
    featured: true,
  },
  {
    id: 2,
    name: "Ibrahim Musa",
    role: "Parent d eleve, Nigeria",
    text: "Ma fille peut enfin aller a l ecole pres de chez nous. Elle apprend a lire et a ecrire.",
    avatar: "IM",
    featured: true,
  },
  {
    id: 3,
    name: "Fatoumata Diallo",
    role: "Habitante, Mali",
    text: "Avant, je marchais 3 heures chaque jour pour chercher de l eau. Maintenant, la pompe est a 5 minutes.",
    avatar: "FD",
    featured: true,
  },
];